class runner_ctrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2023-08-04 23:11:11 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 7
        self.input_vars = ['b']

    def move(self, b):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['a3', 'a4', 'a2', 'a1', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (b == 1):
                self.state = 1

                output["a3"] = False
                output["a4"] = False
                output["a2"] = False
                output["a1"] = True
                output["loc"] = 'c1'
            elif (b == 3):
                self.state = 2

                output["a3"] = False
                output["a4"] = False
                output["a2"] = False
                output["a1"] = True
                output["loc"] = 'c1'
            else:
                self._error(b)
        elif self.state == 1:
            if (b == 2):
                self.state = 3

                output["a3"] = False
                output["a4"] = False
                output["a2"] = True
                output["a1"] = False
                output["loc"] = 'c2'
            else:
                self._error(b)
        elif self.state == 2:
            if (b == 2):
                self.state = 3

                output["a3"] = False
                output["a4"] = False
                output["a2"] = True
                output["a1"] = False
                output["loc"] = 'c2'
            else:
                self._error(b)
        elif self.state == 3:
            if (b == 1):
                self.state = 4

                output["a3"] = False
                output["a4"] = True
                output["a2"] = False
                output["a1"] = False
                output["loc"] = 'c4'
            elif (b == 3):
                self.state = 5

                output["a3"] = False
                output["a4"] = True
                output["a2"] = False
                output["a1"] = False
                output["loc"] = 'c4'
            else:
                self._error(b)
        elif self.state == 4:
            if (b == 2):
                self.state = 6

                output["a3"] = False
                output["a4"] = True
                output["a2"] = False
                output["a1"] = False
                output["loc"] = 'c4'
            else:
                self._error(b)
        elif self.state == 5:
            if (b == 2):
                self.state = 6

                output["a3"] = False
                output["a4"] = True
                output["a2"] = False
                output["a1"] = False
                output["loc"] = 'c4'
            else:
                self._error(b)
        elif self.state == 6:
            if (b == 1):
                self.state = 4

                output["a3"] = False
                output["a4"] = True
                output["a2"] = False
                output["a1"] = False
                output["loc"] = 'c4'
            elif (b == 3):
                self.state = 5

                output["a3"] = False
                output["a4"] = True
                output["a2"] = False
                output["a1"] = False
                output["loc"] = 'c4'
            else:
                self._error(b)
        elif self.state == 7:
            if (b == 2):
                self.state = 0

                output["a3"] = False
                output["a4"] = False
                output["a2"] = False
                output["a1"] = True
                output["loc"] = 'c1'
            else:
                self._error(b)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, b):
        raise ValueError("Unrecognized input: " + (
            "b = {b}; ").format(
                b=b))
