class sys_ctrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2023-08-07 12:18:25 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 56
        self.input_vars = ['vh', 'p', 'light']

    def move(self, vh, p, light):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['a8', 'a7', 'a9', 'a4', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (vh == 2) and (p == 4) and (light == 'g'):
                self.state = 1

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 4) and (light == 'g'):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 3) and (light == 'g'):
                self.state = 0

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'g'):
                self.state = 3

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 3) and (light == 'y'):
                self.state = 4

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'y'):
                self.state = 5

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 1:
            if (vh == 2) and (p == 4) and (light == 'g'):
                self.state = 1

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 4) and (light == 'g'):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 5) and (light == 'g'):
                self.state = 51

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'g'):
                self.state = 46

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 5) and (light == 'y'):
                self.state = 52

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'y'):
                self.state = 47

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 2:
            if (vh == 4) and (p == 4) and (light == 'g'):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (p == 5) and (light == 'g'):
                self.state = 40

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 4) and (light == 'g'):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'g'):
                self.state = 46

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'y'):
                self.state = 47

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 3:
            if (vh == 4) and (p == 4) and (light == 'g'):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (p == 3) and (light == 'g'):
                self.state = 8

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 4) and (light == 'g'):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'g'):
                self.state = 3

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'y'):
                self.state = 5

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 4:
            if (vh == 2) and (p == 3) and (light == 'r'):
                self.state = 45

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'r'):
                self.state = 6

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 5:
            if (vh == 3) and (p == 3) and (light == 'r'):
                self.state = 6

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 6:
            if (vh == 4) and (p == 4) and (light == 'g'):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (p == 3) and (light == 'g'):
                self.state = 8

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 4) and (light == 'g'):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'g'):
                self.state = 3

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'r'):
                self.state = 6

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 7:
            if (vh == 4) and (p == 4) and (light == 'g'):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 4) and (light == 'g'):
                self.state = 9

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (p == 5) and (light == 'g'):
                self.state = 40

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 30

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 31

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 8:
            if (vh == 4) and (p == 4) and (light == 'g'):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 4) and (light == 'g'):
                self.state = 9

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (p == 3) and (light == 'g'):
                self.state = 8

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 3) and (light == 'g'):
                self.state = 10

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 3) and (light == 'y'):
                self.state = 11

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 9:
            if (vh == 6) and (p == 4) and (light == 'g'):
                self.state = 16

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 17

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 18

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 4) and (light == 'g'):
                self.state = 29

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 30

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 31

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 10:
            if (vh == 6) and (p == 4) and (light == 'g'):
                self.state = 13

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (p == 3) and (light == 'g'):
                self.state = 14

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (p == 3) and (light == 'y'):
                self.state = 15

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 4) and (light == 'g'):
                self.state = 9

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 3) and (light == 'g'):
                self.state = 10

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (p == 3) and (light == 'y'):
                self.state = 11

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 11:
            if (vh == 6) and (p == 3) and (light == 'r'):
                self.state = 12

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 12:
            if (vh == 6) and (p == 4) and (light == 'g'):
                self.state = 13

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (p == 3) and (light == 'g'):
                self.state = 14

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (p == 3) and (light == 'r'):
                self.state = 12

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 13:
            if (vh == 6) and (p == 4) and (light == 'g'):
                self.state = 16

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 17

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 18

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 14:
            if (vh == 6) and (p == 4) and (light == 'g'):
                self.state = 13

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (p == 3) and (light == 'g'):
                self.state = 14

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (p == 3) and (light == 'y'):
                self.state = 15

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 15:
            if (vh == 6) and (p == 3) and (light == 'r'):
                self.state = 12

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 16:
            if (vh == 6) and (p == 4) and (light == 'g'):
                self.state = 16

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 17

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 18

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 17:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 23

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 24

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 25

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 26

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 18:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 19

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 19:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 21

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 20:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 21:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 21

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 22:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 21

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 23:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 24:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 19

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 25:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 27

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 28

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 26:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 19

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 27:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 27

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 28

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 28:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 21

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 29:
            if (vh == 6) and (p == 4) and (light == 'g'):
                self.state = 16

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 17

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 18

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 4) and (light == 'g'):
                self.state = 29

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 30

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 31

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 30:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 23

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 24

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 25

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 26

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 32

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 33

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 34

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 35

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 31:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 19

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 32:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 36

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 37

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 33:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 19

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 34:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 27

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 28

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 36

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 37

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 38

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 39

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 35:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 19

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 36:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 36

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 37

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 37:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 21

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 38:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 20

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 22

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'g'):
                self.state = 27

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (p == 5) and (light == 'y'):
                self.state = 28

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 36

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 37

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 38

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 39

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 39:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 21

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, p, light)
        elif self.state == 40:
            if (vh == 4) and (p == 6) and (light == 'g'):
                self.state = 41

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 42

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 43

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 4) and (p == 5) and (light == 'g'):
                self.state = 44

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 30

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 31

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 41:
            if (vh == 4) and (p == 6) and (light == 'g'):
                self.state = 41

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 42

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 43

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 42:
            if (vh == 6) and (p == 6) and (light == 'g'):
                self.state = 23

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (p == 6) and (light == 'y'):
                self.state = 24

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 32

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 33

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 43:
            if (vh == 6) and (p == 6) and (light == 'r'):
                self.state = 19

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, p, light)
        elif self.state == 44:
            if (vh == 4) and (p == 6) and (light == 'g'):
                self.state = 41

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 6) and (light == 'g'):
                self.state = 42

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 6) and (light == 'y'):
                self.state = 43

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 4) and (p == 5) and (light == 'g'):
                self.state = 44

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'g'):
                self.state = 30

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (p == 5) and (light == 'y'):
                self.state = 31

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, p, light)
        elif self.state == 45:
            if (vh == 2) and (p == 4) and (light == 'g'):
                self.state = 1

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 4) and (light == 'g'):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 3) and (light == 'g'):
                self.state = 0

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'g'):
                self.state = 3

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 3) and (light == 'r'):
                self.state = 45

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 3) and (light == 'r'):
                self.state = 6

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 46:
            if (vh == 4) and (p == 6) and (light == 'g'):
                self.state = 41

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 4) and (p == 5) and (light == 'g'):
                self.state = 40

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'g'):
                self.state = 49

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'y'):
                self.state = 50

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'g'):
                self.state = 46

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'y'):
                self.state = 47

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 47:
            if (vh == 3) and (p == 6) and (light == 'r'):
                self.state = 48

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 48:
            if (vh == 4) and (p == 6) and (light == 'g'):
                self.state = 41

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 3) and (p == 6) and (light == 'g'):
                self.state = 49

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'r'):
                self.state = 48

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 49:
            if (vh == 4) and (p == 6) and (light == 'g'):
                self.state = 41

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 3) and (p == 6) and (light == 'g'):
                self.state = 49

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'y'):
                self.state = 50

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 50:
            if (vh == 3) and (p == 6) and (light == 'r'):
                self.state = 48

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 51:
            if (vh == 2) and (p == 6) and (light == 'g'):
                self.state = 54

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'g'):
                self.state = 49

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 6) and (light == 'y'):
                self.state = 55

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'y'):
                self.state = 50

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 5) and (light == 'g'):
                self.state = 51

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'g'):
                self.state = 46

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 5) and (light == 'y'):
                self.state = 52

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 5) and (light == 'y'):
                self.state = 47

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 52:
            if (vh == 2) and (p == 6) and (light == 'r'):
                self.state = 53

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'r'):
                self.state = 48

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 53:
            if (vh == 2) and (p == 6) and (light == 'g'):
                self.state = 54

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'g'):
                self.state = 49

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 6) and (light == 'r'):
                self.state = 53

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'r'):
                self.state = 48

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 54:
            if (vh == 2) and (p == 6) and (light == 'g'):
                self.state = 54

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'g'):
                self.state = 49

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (p == 6) and (light == 'y'):
                self.state = 55

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'y'):
                self.state = 50

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 55:
            if (vh == 2) and (p == 6) and (light == 'r'):
                self.state = 53

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (p == 6) and (light == 'r'):
                self.state = 48

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        elif self.state == 56:
            if (vh == 2) and (p == 3) and (light == 'g'):
                self.state = 0

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, p, light)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, vh, p, light):
        raise ValueError("Unrecognized input: " + (
            "vh = {vh}; "
            "p = {p}; "
            "light = {light}; ").format(
                vh=vh,
                p=p,
                light=light))
