class sys_ctrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2023-09-14 02:08:49 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 103
        self.input_vars = ['vh', 'light', 'p']

    def move(self, vh, light, p):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['a8', 'a7', 'a9', 'a4', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (vh == 2) and (light == 'g2') and (p == 4):
                self.state = 1

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 4):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'g2') and (p == 3):
                self.state = 3

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 3):
                self.state = 4

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 1:
            if (vh == 2) and (light == 'g3') and (p == 4):
                self.state = 86

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'g3') and (p == 5):
                self.state = 95

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 4):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 5):
                self.state = 71

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 2:
            if (vh == 4) and (light == 'g3') and (p == 4):
                self.state = 5

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g3') and (p == 5):
                self.state = 58

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 4):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 5):
                self.state = 71

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 3:
            if (vh == 2) and (light == 'g3') and (p == 4):
                self.state = 86

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 4):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'g3') and (p == 3):
                self.state = 87

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 3):
                self.state = 8

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 4:
            if (vh == 4) and (light == 'g3') and (p == 4):
                self.state = 5

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g3') and (p == 3):
                self.state = 6

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 4):
                self.state = 7

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 3):
                self.state = 8

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 5:
            if (vh == 4) and (light == 'y1') and (p == 4):
                self.state = 9

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'y1') and (p == 5):
                self.state = 66

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 4):
                self.state = 25

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 5):
                self.state = 56

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 6:
            if (vh == 4) and (light == 'y1') and (p == 4):
                self.state = 9

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 4):
                self.state = 25

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'y1') and (p == 3):
                self.state = 10

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 3):
                self.state = 26

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 7:
            if (vh == 4) and (light == 'y1') and (p == 4):
                self.state = 9

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'y1') and (p == 5):
                self.state = 66

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 4):
                self.state = 11

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 5):
                self.state = 73

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 8:
            if (vh == 4) and (light == 'y1') and (p == 4):
                self.state = 9

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'y1') and (p == 3):
                self.state = 10

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 4):
                self.state = 11

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 3):
                self.state = 12

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 9:
            if (vh == 5) and (light == 'y2') and (p == 5):
                self.state = 55

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 10:
            if (vh == 5) and (light == 'y2') and (p == 3):
                self.state = 28

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 11:
            if (vh == 3) and (light == 'y2') and (p == 5):
                self.state = 75

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 12:
            if (vh == 3) and (light == 'y2') and (p == 3):
                self.state = 13

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 13:
            if (vh == 3) and (light == 'r') and (p == 3):
                self.state = 14

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 14:
            if (vh == 4) and (light == 'g1') and (p == 4):
                self.state = 15

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g1') and (p == 3):
                self.state = 16

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g1') and (p == 4):
                self.state = 17

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g1') and (p == 3):
                self.state = 18

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'r') and (p == 3):
                self.state = 14

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 15:
            if (vh == 4) and (light == 'g2') and (p == 4):
                self.state = 19

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g2') and (p == 5):
                self.state = 67

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g2') and (p == 4):
                self.state = 83

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g2') and (p == 5):
                self.state = 85

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 16:
            if (vh == 4) and (light == 'g2') and (p == 4):
                self.state = 19

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g2') and (p == 4):
                self.state = 83

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g2') and (p == 3):
                self.state = 20

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g2') and (p == 3):
                self.state = 84

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 17:
            if (vh == 4) and (light == 'g2') and (p == 4):
                self.state = 19

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g2') and (p == 5):
                self.state = 67

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 4):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 5):
                self.state = 68

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 18:
            if (vh == 4) and (light == 'g2') and (p == 4):
                self.state = 19

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g2') and (p == 3):
                self.state = 20

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 4):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 3):
                self.state = 4

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 19:
            if (vh == 4) and (light == 'g3') and (p == 4):
                self.state = 5

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g3') and (p == 5):
                self.state = 58

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 4):
                self.state = 21

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 5):
                self.state = 59

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 20:
            if (vh == 4) and (light == 'g3') and (p == 4):
                self.state = 5

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 4):
                self.state = 21

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g3') and (p == 3):
                self.state = 6

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 3):
                self.state = 22

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 21:
            if (vh == 6) and (light == 'y1') and (p == 4):
                self.state = 23

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'y1') and (p == 5):
                self.state = 36

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 4):
                self.state = 25

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 5):
                self.state = 56

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 22:
            if (vh == 6) and (light == 'y1') and (p == 4):
                self.state = 23

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'y1') and (p == 3):
                self.state = 24

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 4):
                self.state = 25

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 3):
                self.state = 26

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 23:
            if (vh == 6) and (light == 'y2') and (p == 5):
                self.state = 38

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 24:
            if (vh == 6) and (light == 'y2') and (p == 3):
                self.state = 27

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 25:
            if (vh == 6) and (light == 'y2') and (p == 5):
                self.state = 38

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y2') and (p == 5):
                self.state = 55

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 26:
            if (vh == 6) and (light == 'y2') and (p == 3):
                self.state = 27

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y2') and (p == 3):
                self.state = 28

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 27:
            if (vh == 6) and (light == 'r') and (p == 3):
                self.state = 29

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 28:
            if (vh == 6) and (light == 'r') and (p == 3):
                self.state = 29

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 29:
            if (vh == 6) and (light == 'g1') and (p == 4):
                self.state = 30

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g1') and (p == 3):
                self.state = 31

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'r') and (p == 3):
                self.state = 29

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 30:
            if (vh == 6) and (light == 'g2') and (p == 4):
                self.state = 32

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g2') and (p == 5):
                self.state = 54

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 31:
            if (vh == 6) and (light == 'g2') and (p == 4):
                self.state = 32

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g2') and (p == 3):
                self.state = 33

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 32:
            if (vh == 6) and (light == 'g3') and (p == 4):
                self.state = 34

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g3') and (p == 5):
                self.state = 51

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 33:
            if (vh == 6) and (light == 'g3') and (p == 4):
                self.state = 34

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g3') and (p == 3):
                self.state = 35

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 34:
            if (vh == 6) and (light == 'y1') and (p == 4):
                self.state = 23

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'y1') and (p == 5):
                self.state = 36

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 35:
            if (vh == 6) and (light == 'y1') and (p == 4):
                self.state = 23

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'y1') and (p == 3):
                self.state = 24

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 36:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 37

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'y2') and (p == 5):
                self.state = 38

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 37:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 39

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 38:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 39

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 39:
            if (vh == 6) and (light == 'g1') and (p == 6):
                self.state = 40

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'r') and (p == 6):
                self.state = 39

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 40:
            if (vh == 6) and (light == 'g2') and (p == 6):
                self.state = 41

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 41:
            if (vh == 6) and (light == 'g3') and (p == 6):
                self.state = 42

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 42:
            if (vh == 6) and (light == 'y1') and (p == 6):
                self.state = 43

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, light, p)
        elif self.state == 43:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 44

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, light, p)
        elif self.state == 44:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 45

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 45:
            if (vh == 6) and (light == 'g1') and (p == 6):
                self.state = 46

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            elif (vh == 6) and (light == 'r') and (p == 6):
                self.state = 45

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 46:
            if (vh == 6) and (light == 'g2') and (p == 6):
                self.state = 47

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 47:
            if (vh == 6) and (light == 'g3') and (p == 6):
                self.state = 48

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 48:
            if (vh == 6) and (light == 'y1') and (p == 6):
                self.state = 49

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 49:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 50

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 50:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 45

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 51:
            if (vh == 6) and (light == 'y1') and (p == 6):
                self.state = 43

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (light == 'y1') and (p == 5):
                self.state = 52

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, light, p)
        elif self.state == 52:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 44

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (light == 'y2') and (p == 5):
                self.state = 53

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, light, p)
        elif self.state == 53:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 45

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 54:
            if (vh == 6) and (light == 'g3') and (p == 6):
                self.state = 42

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g3') and (p == 5):
                self.state = 51

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 55:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 39

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 56:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 37

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'y2') and (p == 5):
                self.state = 38

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y2') and (p == 6):
                self.state = 57

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y2') and (p == 5):
                self.state = 55

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 57:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 39

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 58:
            if (vh == 4) and (light == 'y1') and (p == 6):
                self.state = 64

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 6):
                self.state = 65

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'y1') and (p == 5):
                self.state = 66

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 5):
                self.state = 56

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 59:
            if (vh == 6) and (light == 'y1') and (p == 6):
                self.state = 43

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 6) and (light == 'y1') and (p == 5):
                self.state = 52

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (light == 'y1') and (p == 6):
                self.state = 60

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (light == 'y1') and (p == 5):
                self.state = 61

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, light, p)
        elif self.state == 60:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 44

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (light == 'y2') and (p == 6):
                self.state = 62

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, light, p)
        elif self.state == 61:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 44

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 6) and (light == 'y2') and (p == 5):
                self.state = 53

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (light == 'y2') and (p == 6):
                self.state = 62

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            elif (vh == 5) and (light == 'y2') and (p == 5):
                self.state = 63

                output["a8"] = False
                output["a7"] = False
                output["a9"] = False
                output["a4"] = True
                output["loc"] = 'c4'
            else:
                self._error(vh, light, p)
        elif self.state == 62:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 45

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 63:
            if (vh == 6) and (light == 'r') and (p == 6):
                self.state = 45

                output["a8"] = False
                output["a7"] = False
                output["a9"] = True
                output["a4"] = False
                output["loc"] = 'c9'
            else:
                self._error(vh, light, p)
        elif self.state == 64:
            if (vh == 5) and (light == 'y2') and (p == 6):
                self.state = 57

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 65:
            if (vh == 6) and (light == 'y2') and (p == 6):
                self.state = 37

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y2') and (p == 6):
                self.state = 57

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 66:
            if (vh == 5) and (light == 'y2') and (p == 6):
                self.state = 57

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y2') and (p == 5):
                self.state = 55

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 67:
            if (vh == 4) and (light == 'g3') and (p == 6):
                self.state = 69

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 6):
                self.state = 81

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g3') and (p == 5):
                self.state = 58

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 5):
                self.state = 59

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 68:
            if (vh == 4) and (light == 'g3') and (p == 6):
                self.state = 69

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'g3') and (p == 5):
                self.state = 58

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 6):
                self.state = 70

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 5):
                self.state = 71

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 69:
            if (vh == 4) and (light == 'y1') and (p == 6):
                self.state = 64

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'y1') and (p == 6):
                self.state = 65

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 70:
            if (vh == 4) and (light == 'y1') and (p == 6):
                self.state = 64

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 6):
                self.state = 72

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 71:
            if (vh == 4) and (light == 'y1') and (p == 6):
                self.state = 64

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 4) and (light == 'y1') and (p == 5):
                self.state = 66

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 6):
                self.state = 72

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 5):
                self.state = 73

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 72:
            if (vh == 3) and (light == 'y2') and (p == 6):
                self.state = 74

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 73:
            if (vh == 3) and (light == 'y2') and (p == 6):
                self.state = 74

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y2') and (p == 5):
                self.state = 75

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 74:
            if (vh == 3) and (light == 'r') and (p == 6):
                self.state = 76

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 75:
            if (vh == 3) and (light == 'r') and (p == 6):
                self.state = 76

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 76:
            if (vh == 4) and (light == 'g1') and (p == 6):
                self.state = 77

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g1') and (p == 6):
                self.state = 78

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'r') and (p == 6):
                self.state = 76

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 77:
            if (vh == 4) and (light == 'g2') and (p == 6):
                self.state = 79

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g2') and (p == 6):
                self.state = 82

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 78:
            if (vh == 4) and (light == 'g2') and (p == 6):
                self.state = 79

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 6):
                self.state = 80

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 79:
            if (vh == 4) and (light == 'g3') and (p == 6):
                self.state = 69

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 6):
                self.state = 81

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 80:
            if (vh == 4) and (light == 'g3') and (p == 6):
                self.state = 69

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 6):
                self.state = 70

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 81:
            if (vh == 6) and (light == 'y1') and (p == 6):
                self.state = 43

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            elif (vh == 5) and (light == 'y1') and (p == 6):
                self.state = 60

                output["a8"] = True
                output["a7"] = False
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c8'
            else:
                self._error(vh, light, p)
        elif self.state == 82:
            if (vh == 6) and (light == 'g3') and (p == 6):
                self.state = 42

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 6):
                self.state = 81

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 83:
            if (vh == 6) and (light == 'g3') and (p == 4):
                self.state = 34

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g3') and (p == 5):
                self.state = 51

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 4):
                self.state = 21

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 5):
                self.state = 59

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 84:
            if (vh == 6) and (light == 'g3') and (p == 4):
                self.state = 34

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g3') and (p == 3):
                self.state = 35

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 4):
                self.state = 21

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 3):
                self.state = 22

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 85:
            if (vh == 6) and (light == 'g3') and (p == 6):
                self.state = 42

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 6) and (light == 'g3') and (p == 5):
                self.state = 51

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 6):
                self.state = 81

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 5) and (light == 'g3') and (p == 5):
                self.state = 59

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 86:
            if (vh == 2) and (light == 'y1') and (p == 4):
                self.state = 88

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'y1') and (p == 5):
                self.state = 97

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 4):
                self.state = 11

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 5):
                self.state = 73

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 87:
            if (vh == 2) and (light == 'y1') and (p == 4):
                self.state = 88

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 4):
                self.state = 11

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'y1') and (p == 3):
                self.state = 89

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 3):
                self.state = 12

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 88:
            if (vh == 2) and (light == 'y2') and (p == 5):
                self.state = 99

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y2') and (p == 5):
                self.state = 75

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 89:
            if (vh == 2) and (light == 'y2') and (p == 3):
                self.state = 90

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y2') and (p == 3):
                self.state = 13

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 90:
            if (vh == 2) and (light == 'r') and (p == 3):
                self.state = 91

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'r') and (p == 3):
                self.state = 14

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 91:
            if (vh == 2) and (light == 'g1') and (p == 4):
                self.state = 92

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g1') and (p == 4):
                self.state = 17

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'g1') and (p == 3):
                self.state = 0

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g1') and (p == 3):
                self.state = 18

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'r') and (p == 3):
                self.state = 91

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'r') and (p == 3):
                self.state = 14

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 92:
            if (vh == 2) and (light == 'g2') and (p == 4):
                self.state = 1

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'g2') and (p == 5):
                self.state = 93

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 4):
                self.state = 2

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 5):
                self.state = 68

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 93:
            if (vh == 2) and (light == 'g3') and (p == 6):
                self.state = 94

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 6):
                self.state = 70

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'g3') and (p == 5):
                self.state = 95

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 5):
                self.state = 71

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 94:
            if (vh == 2) and (light == 'y1') and (p == 6):
                self.state = 96

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 6):
                self.state = 72

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 95:
            if (vh == 2) and (light == 'y1') and (p == 6):
                self.state = 96

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 6):
                self.state = 72

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'y1') and (p == 5):
                self.state = 97

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y1') and (p == 5):
                self.state = 73

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 96:
            if (vh == 2) and (light == 'y2') and (p == 6):
                self.state = 98

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y2') and (p == 6):
                self.state = 74

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 97:
            if (vh == 2) and (light == 'y2') and (p == 6):
                self.state = 98

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y2') and (p == 6):
                self.state = 74

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'y2') and (p == 5):
                self.state = 99

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'y2') and (p == 5):
                self.state = 75

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 98:
            if (vh == 2) and (light == 'r') and (p == 6):
                self.state = 100

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'r') and (p == 6):
                self.state = 76

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 99:
            if (vh == 2) and (light == 'r') and (p == 6):
                self.state = 100

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'r') and (p == 6):
                self.state = 76

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 100:
            if (vh == 2) and (light == 'g1') and (p == 6):
                self.state = 101

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g1') and (p == 6):
                self.state = 78

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 2) and (light == 'r') and (p == 6):
                self.state = 100

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'r') and (p == 6):
                self.state = 76

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 101:
            if (vh == 2) and (light == 'g2') and (p == 6):
                self.state = 102

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g2') and (p == 6):
                self.state = 80

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 102:
            if (vh == 2) and (light == 'g3') and (p == 6):
                self.state = 94

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            elif (vh == 3) and (light == 'g3') and (p == 6):
                self.state = 70

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        elif self.state == 103:
            if (vh == 2) and (light == 'g1') and (p == 3):
                self.state = 0

                output["a8"] = False
                output["a7"] = True
                output["a9"] = False
                output["a4"] = False
                output["loc"] = 'c7'
            else:
                self._error(vh, light, p)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, vh, light, p):
        raise ValueError("Unrecognized input: " + (
            "vh = {vh}; "
            "light = {light}; "
            "p = {p}; ").format(
                vh=vh,
                light=light,
                p=p))
